APIKEY = "057fa467-501a-47b8-9b23-36041d1a8388"
USERNAME = "Bot"

[GROUPS."Isaac Trustworthiness"] # in Jan, not in Jan, none
"https://manifold.markets/jack/will-isaacking-lose-his-trustworthy" = ["YES", "NO", "NO"]
"https://manifold.markets/Courtney/isaacking-and-destiny-together-mani-42332c90e971" = ["YES", "NO", "NO"]
"https://manifold.markets/jack/will-isaacking-lose-his-trustworthy-ec06dc536f2c" = ["YES", 0, "NO"]
"https://manifold.markets/IsaacKing/will-i-lose-my-trustworthy-ish-badg" = ["YES", 0, "NO"]

[GROUPS."Monkeypox Jan 10"] # [84.3k, 84.5), [84.5, 84.8), 84800<=x<85k, [85k, 85.2), >=85.2k, none
"https://manifold.markets/GeneFama/will-there-be-84300-confirmed-cases" = ["YES", "YES", "YES", "YES", "YES", "NO"]
"https://manifold.markets/GeneFama/will-there-be-84500-confirmed-cases-3e0043c1dfed" = ["NO", "YES", "YES", "YES", "YES", "NO"]
"https://manifold.markets/GeneFama/will-there-be-84800-confirmed-cases" = ["NO", "NO", "YES", "YES", "YES", "NO"]
"https://manifold.markets/GeneFama/will-there-be-85000-confirmed-cases-6e7e2b9d9c75" = ["NO", "NO", "NO", "YES", "YES", "NO"]
"https://manifold.markets/GeneFama/will-there-be-85200-confirmed-cases" = ["NO", "NO", "NO", "NO", "YES", "NO"]

# Prices will change if we arb on the above group so it will fuck this one
# [GROUPS."Monkeypox >=85k"] # by Jan 10, after jan 10 before eom, none
# "https://manifold.markets/GeneFama/will-there-be-85000-confirmed-cases-6e7e2b9d9c75" = ["YES", "NO", "NO"]
# "https://manifold.markets/egroj/will-there-be-85000-confirmed-cases-1653cfa1ac3b" = ["YES", "YES", "NO"]

[GROUPS."Monkeypox average"] # below 35, 30, 25, 20, 15, 10, none
"https://manifold.markets/egroj/will-mpox-monkeypox-7day-average-ca" = ["YES", "YES", "YES", "YES", "YES", "YES", "NO"]
"https://manifold.markets/egroj/will-mpox-monkeypox-7day-average-ca-8d7f3b3669c8" = ["NO", "YES", "YES", "YES", "YES", "YES", "NO"]
"https://manifold.markets/egroj/will-mpox-monkeypox-7day-average-ca-4d8e01b57e33" = ["NO", "NO", "YES", "YES", "YES", "YES", "NO"]
"https://manifold.markets/egroj/will-mpox-monkeypox-7day-average-ca-31db52af11d9" = ["NO", "NO", "NO", "YES", "YES", "YES", "NO"]
"https://manifold.markets/egroj/will-mpox-monkeypox-7day-average-ca-362d6729accc" = ["NO", "NO", "NO", "NO", "YES", "YES", "NO"]
"https://manifold.markets/egroj/will-mpox-monkeypox-7day-average-ca-8a43e5b128c6" = ["NO", "NO", "NO", "NO", "NO", "YES", "NO"]

[GROUPS.Biden2ndTerm]
"https://manifold.markets/NcyRocks/will-joe-biden-run-for-president-in" = [ "YES", "NO"]
"https://manifold.markets/LivInTheLookingGlass/will-joe-biden-seek-a-second-term-i" = [ "YES", "NO"]

[GROUPS.Putin2023]
"https://manifold.markets/ahalekelly/will-vladimir-putin-still-be-the-le" = [ "YES", "NO"]
"https://manifold.markets/njmkw/if-ukraine-recaptures-cherson-in-20-abc72a4594fc" = [ "YES", "NO"]

[GROUPS.BidenImpeached]
"https://manifold.markets/Predictor/will-joe-biden-get-impeached-in-his" = [ "YES", "NO"]
"https://manifold.markets/MP/will-biden-be-impeached-by-2025" = [ "YES", "NO"]

[GROUPS.2030Hosts]
"https://manifold.markets/Nostradamnedus/will-australia-host-or-cohost-the-2" = [ "YES", "NO", "NO", "NO", "NO", "NO"]
"https://manifold.markets/egroj/will-spain-and-portugal-cohost-the" = [ "NO", "YES", "NO", "NO", "NO", "NO"]
"https://manifold.markets/egroj/will-morocco-host-the-2030-fifa-wor" = [ "NO", "NO", "YES", "NO", "NO", "NO"]
"https://manifold.markets/egroj/will-south-america-host-the-2030-fi" = [ "NO", "NO", "NO", "YES", "NO", "NO"]
"https://manifold.markets/egroj/will-china-host-the-2030-fifa-world" = [ "NO", "NO", "NO", "NO", "YES", "NO"]

[GROUPS.BidenVSTrump]
"https://manifold.markets/MarketManagerBot/will-the-2024-presidential-race-be" = [ "YES", "NO"]
"https://manifold.markets/BoltonBailey/will-the-2024-election-be-a-bidentr" = [ "YES", "NO"]

[GROUPS."Democratic Nominee"] # Biden, Harris, Warren, Newsom, Buttigieg, Psaki, Other
"https://manifold.markets/NathanpmYoung/will-biden-be-the-2024-democratic-n" = ["YES", "NO", "NO", "NO", "NO", "NO", "NO"]
"https://manifold.markets/MarketManagerBot/will-kamala-harris-be-the-democrati" = ["NO", "YES", "NO", "NO", "NO", "NO", "NO"]
"https://manifold.markets/MarketManagerBot/will-elizabeth-warren-be-the-democr" = ["NO", "NO", "YES", "NO", "NO", "NO", "NO"]
"https://manifold.markets/MarketManagerBot/will-gavin-newsom-be-the-democratic" = ["NO", "NO", "NO", "YES", "NO", "NO", "NO"]
"https://manifold.markets/JamesGrugett/will-pete-buttigieg-be-the-2024-dem" = ["NO", "NO", "NO", "NO", "YES", "NO", "NO"]
"https://manifold.markets/dglid/will-jen-psaki-be-the-2024-democrat" = ["NO", "NO", "NO", "NO", "NO", "YES", "NO"]

"https://manifold.markets/Charlie/will-someone-other-than-biden-harri" = ["NO", "NO", "YES", "NO", "NO", "YES", "YES"]


[GROUPS."Republican Nominee"] # DeSantis, Trump, Pence, Haley, Pompeo, Youngkin, Other
"https://manifold.markets/SG/will-ron-desantis-be-the-2024-repub" = ["YES", "NO", "NO", "NO", "NO", "NO", "NO"]
"https://manifold.markets/BruceGrugett/will-donald-trump-be-the-republican" = ["NO", "YES", "NO", "NO", "NO", "NO", "NO"]
"https://manifold.markets/RichardShu/will-donald-trump-be-the-republican-1120636b600a" = ["NO", "YES", "NO", "NO", "NO", "NO", "NO"]
"https://manifold.markets/Gigacasting/will-mike-pence-be-the-republican-n" = ["NO", "NO", "YES", "NO", "NO", "NO", "NO"]
"https://manifold.markets/MarketManagerBot/will-nikki-haley-be-the-republican" = ["NO", "NO", "NO", "YES", "NO", "NO", "NO"]
"https://manifold.markets/MarketManagerBot/will-mike-pompeo-be-the-republican" = ["NO", "NO", "NO", "NO", "YES", "NO", "NO"]
"https://manifold.markets/JimAusman/will-virginia-governor-glenn-youngk" = ["NO", "NO", "NO", "NO", "NO", "YES", "NO"]

"https://manifold.markets/Gigacasting/will-the-republican-nominee-be-eith" = ["YES", "YES", "NO", "NO", "NO", "NO", "NO"]

[GROUPS."Winner of 2024 Presidential Election"] # Biden, Trump, DeSantis, Newsom, Other
"https://manifold.markets/LarsDoucet/will-joe-biden-win-the-2024-us-pres" = ["YES", "NO", "NO", "NO", "NO"]
"https://manifold.markets/LarsDoucet/will-donald-trump-win-the-2024-us-p" = ["NO", "YES", "NO", "NO", "NO"]
"https://manifold.markets/jack/will-ron-desantis-be-elected-us-pre" = ["NO", "NO", "YES", "NO", "NO"]
"https://manifold.markets/MartinRandall/will-gavin-newsom-win-the-2024-pres" = ["NO", "NO", "NO", "YES", "NO"]

"https://manifold.markets/April/will-either-joe-biden-or-donald-tru" = ["YES", "YES", "NO", "NO", "NO"]

[GROUPS."Tesla CEO"] # steps down in eoy 2023 and not new ceo, and new  ceo, forced out in 2023 and not new ceo, and new ceo in 2023, stays CEO 2023
"https://manifold.markets/kolotom99/will-elon-musk-be-teslas-ceo-throug" = ["NO", "NO", "NO", "NO", "YES"]
"https://manifold.markets/ManifoldMarkets/will-elon-musk-step-down-from-being" = ["YES", "YES", "NO", "NO", "NO"]
"https://manifold.markets/BTE/will-elon-musk-appoint-a-replacemen" = ["NO", "YES", "NO", "YES", "NO"]
"https://manifold.markets/Bot/will-elon-musk-be-forced-out-as-tes" = ["NO", "NO", "YES", "YES", "NO"]

[GROUPS."Musk Richest Man"]
"https://manifold.markets/ShakedKoplewitz/will-elon-musk-be-the-richest-man-i-7f9a0ec3e42e" = ["YES", "NO"]
"https://manifold.markets/ShakedKoplewitz/will-elon-musk-be-the-richest-man-i" = ["YES", "NO"]

# [GROUPS."Next Speaker of the House"] # McCarthy <218, McCarthy >=218, Scalise, Jordan, Trump, Upton, Not a member whos not trump or upton, None
# "https://manifold.markets/BTE/will-kevin-mccarthy-be-the-next-spe" = ["YES", "YES", "NO", "NO", "NO", "NO", "NO", "NO"]
# "https://manifold.markets/jack/will-kevin-mccarthy-be-next-speaker" = ["YES", "YES", "NO", "NO", "NO", "NO", "NO", "NO"]
# "https://manifold.markets/BoltonBailey/will-kevin-mccarthy-be-the-next-spe-c8186c01015f" = ["YES", "YES", "NO", "NO", "NO", "NO", "NO", "NO"]

# "https://manifold.markets/jack/will-mccarthy-be-elected-next-speak" = ["YES", "NO", "NO", "NO", "NO", "NO", "NO", "NO"]

# "https://manifold.markets/BTE/will-kevin-mccarthy-get-more-votes" = [0, "YES", 0, 0, 0, 0, 0, "NO"]

# "https://manifold.markets/jack/will-jim-jordan-be-next-speaker-of" = ["NO", "NO", "YES", "NO", "NO", "NO", "NO", "NO"]

# "https://manifold.markets/jack/will-steve-scalise-rla-be-next-spea" = ["NO", "NO", "NO", "YES", "NO", "NO", "NO", "NO"]

# "https://manifold.markets/BTE/will-donald-trump-be-the-next-speak" = ["NO", "NO", "NO", "NO", "YES", "NO", "NO", "NO"]

# "https://manifold.markets/BTE/will-fred-upton-be-elected-speaker" = ["NO", "NO", "NO", "NO", "NO", "YES", "NO", "NO"]

# "https://manifold.markets/BTE/will-the-house-elect-a-speaker-who" = ["NO", "NO", "NO", "NO", "YES", "YES", "YES", "NO"]
# "https://manifold.markets/jack/will-the-next-speaker-of-the-house" = ["NO", "NO", "NO", "NO", "YES", "YES", "YES", "NO"]

# [GROUPS."Speaker of the House Date"] # [now, Friday], (Friday, 14], (14, 31], in Feb, none
# "https://manifold.markets/AlexLiesman/will-we-have-a-speaker-of-the-house" = ["YES", "NO", "NO", "NO", "NO"]
# "https://manifold.markets/jack/will-the-next-speaker-of-the-house-6343de212294" = ["YES", "NO", "NO", "NO", "NO"]
# "https://manifold.markets/BoltonBailey/will-the-next-speaker-of-the-house-e36e7e54da5e" = ["YES", "NO", "NO", "NO", "NO"]

# "https://manifold.markets/PeterWildeford/will-we-get-a-speaker-of-the-house" = ["YES", "YES", "NO", "NO", "NO"]

# "https://manifold.markets/Deeve/will-the-speaker-of-the-house-be-ch" = ["YES", "YES", "YES", "NO", "NO"]

# "https://manifold.markets/BoltonBailey/will-a-new-speaker-of-the-house-be" = ["YES", "YES", "YES", "YES", "NO"]

# [GROUPS."Speaker of the House no. of Ballots"] # 14, 15, (15, 20], (20, 30], none
# "https://manifold.markets/AndrewG/will-the-speaker-of-the-united-stat-960877dc9c47" = ["YES", "NO", "NO", "NO", "NO"]
# "https://manifold.markets/AndrewG/will-the-speaker-of-the-united-stat-65f9c6ce274b" = ["NO", "YES", "NO", "NO", "NO"]
# "https://manifold.markets/AndrewG/will-the-speaker-of-the-united-stat-d5d1cd946b2b" = ["NO", "NO", "YES", "YES", "YES"]
# "https://manifold.markets/jack/will-the-next-speaker-of-the-house-038cdc36cc58" = ["YES", "YES", "YES", "NO", "NO"]
# "https://manifold.markets/MichaelBlume/will-the-next-speaker-of-the-house-cebea93804f7" = ["YES", "YES", "YES", "YES", "NO"]
 
[GROUPS."Fun Market"] # YES, NO, none (if PROB payout >= 0)
"https://manifold.markets/levifinkelstein/will-this-market-be-in-the-interval" = ["YES", "YES", "YES",
                                                                                  "NO", "NO", "NO",
                                                                                  0, 0, 0]
"https://manifold.markets/Fion/will-the-linked-market-by-levi-fink" = ["YES", "NO", 0,
                                                                       "YES", "NO", 0,
                                                                       "YES", "NO", 0]
"https://manifold.markets/Bot/will-the-two-linked-markets-resolve" = ["NO", "YES", "YES",
                                                                      "YES", "NO", "YES",
                                                                      "YES", "YES", "NO"]
"https://manifold.markets/Bot/will-the-linked-market-resolve-na-o" = ["NO", "NO", "YES",
                                                                      "NO", "NO", "YES",
                                                                      "NO", "NO", "YES"]

[GROUPS."Nuclear Weapons Detonation 2023"]
"https://manifold.markets/Gigacasting/will-a-nuclear-weapon-be-detonated-b71e74f6a8e4" = ["YES", "NO"]
"https://manifold.markets/jack/will-a-nuclear-weapon-be-detonated-af0ba4d66245" = ["YES", "NO"]

[GROUPS."Russia Mobilisation"]
"https://manifold.markets/Nostradamnedus/will-russia-begin-a-new-wave-of-mob" = ["YES", "NO", "NO"]
"https://manifold.markets/kolotom99/will-russia-begin-a-new-wave-of-mob-bb11ce38d81f" = ["YES", "YES", "NO"]

[GROUPS."Trump Indictment"] # in Jan, in Feb, in March, in 2023 bar Jan, Feb, none
"https://manifold.markets/belikewater/will-trump-be-indicted-for-any-crim" = ["YES", "NO", "NO","NO", "NO"]
"https://manifold.markets/belikewater/will-trump-be-indicted-for-any-crim-46f07e93f72b" = ["YES", "YES", "NO","NO", "NO"]
"https://manifold.markets/Gigacasting/will-trump-be-indicted-by-march-31" = ["YES", "YES", "YES", "NO", "NO"]
"https://manifold.markets/ACXBot/23-will-donald-trump-get-indicted-o" = ["YES", "YES", "YES", "YES", "NO"]
"https://manifold.markets/LivInTheLookingGlass/will-donald-trump-be-indicted-for-a-bd5ee56971ea" = ["YES", "YES", "YES", "YES", "NO"]

[GROUPS."Amazon Layoffs"] # [9, 11), >=11, none
"https://manifold.markets/firstuserhere/will-amazon-lay-of-9k-or-more-peopl" = ["YES", "YES", "NO"]
"https://manifold.markets/firstuserhere/will-amazon-lay-off-11k-or-more-peo" = ["NO", "YES", "NO"]

# [GROUPS."SBF Tweet"]
# "https://manifold.markets/AmmonLam/will-sbf-make-a-tweet-before-jan-10-59daae1923b8" = ["YES", "NO", "NO", "NO"]
# "https://manifold.markets/AmmonLam/will-sbf-make-a-tweet-before-jan-20-a701ae3c672d" = ["YES", "YES", "NO", "NO"]
# "https://manifold.markets/AmmonLam/will-sbf-make-a-tweet-before-jan-30-e6e58debe4fc" = ["YES", "YES", "YES", "NO"]

[GROUPS."SBF Sentence Length"] # [10, 20), [20, 50), >=50, none
"https://manifold.markets/Gigacasting/will-sbf-be-sentenced-to-10-years" = ["YES", "YES", "YES", "NO"]
"https://manifold.markets/BenjaminIkuta/does-sbf-get-a-sentence-of-20-years" = ["NO", "YES", "YES", "NO"]
"https://manifold.markets/Gigacasting/will-sbf-be-sentenced-to-20-years" = ["NO", "YES", "YES", "NO"]
"https://manifold.markets/GeorgeVii/does-sbf-get-a-lifesentence" = ["NO", "NO", "YES", "NO"]

[GROUPS."Sam Sentence Length"] # [1, 4], >4, none
"https://manifold.markets/GeorgeVii/does-sam-trabucco-get-1-year-senten" = ["YES", "YES", "NO"]
"https://manifold.markets/GeorgeVii/does-sam-trabucco-get-4-years-sente" = ["NO", "YES", "NO"]

[GROUPS."SBF in Jail"]
"https://manifold.markets/GeneFama/will-sbf-be-physically-in-jail-on-j" = ["YES", "NO", "NO", "NO", "NO"]
"https://manifold.markets/GeneFama/will-sbf-be-physically-in-jail-on-f" = ["YES", "YES", "NO", "NO", "NO"]
"https://manifold.markets/GeneFama/will-sbf-be-physically-in-jail-on-m" = ["YES", "YES", "YES", "NO", "NO"]
"https://manifold.markets/GeneFama/will-sbf-be-physically-in-jail-on-a" = ["YES", "YES", "YES", "YES", "NO"]

[GROUPS."SBF Jail Time"]
"https://manifold.markets/Gigacasting/will-sbf-spend-at-least-one-year-in" = ["YES", "NO", "NO", "NO"]
"https://manifold.markets/Gigacasting/will-sbf-spend-at-least-three-month" = ["YES", "YES", "NO", "NO"]
"https://manifold.markets/Gigacasting/will-sbf-spend-at-least-one-month-i" = ["YES", "YES", "YES", "NO"]

[GROUPS."Santos"] # Expelled, retires/etc, none
"https://manifold.markets/jack/will-george-santos-rny-be-expelled" = ["YES", "NO", "NO"]
"https://manifold.markets/lisamarsh/will-rep-george-santos-rny-remain-i" = ["NO", "NO", "YES"]

[GROUPS."Pope Francis"] # resigns 2023, no longer in 2023 not resigned, is for 2023 but no longer in 2024 and not new pope, and new pope by 17th December 2024, still pope 2024
"https://manifold.markets/jack/will-pope-francis-resign-by-end-of" = ["YES", "NO", "NO", "NO", "NO"]
"https://manifold.markets/kolotom99/will-pope-francis-jorge-m-bergoglio" = ["NO", "NO", "YES", "YES", "YES"]
"https://manifold.markets/kolotom99/will-pope-francis-jorge-m-bergoglio-f2b1667dab11" = ["NO", "NO", "NO", "NO", "YES"]
"https://manifold.markets/humblestumble/will-there-be-a-new-pope-elected-by" = ["YES", "YES", "NO", "YES", "NO"]

[GROUPS."US Government Shutdown 2023"]
"https://manifold.markets/brwa/will-there-be-a-government-shutdown" = ["YES", "NO"]
"https://manifold.markets/Nostradamnedus/will-there-be-a-us-government-shutd-26492e3c554d" = ["YES", "NO"]
"https://manifold.markets/connorcash/will-there-be-a-us-government-shutd" = ["YES", "NO"]
# "https://manifold.markets/EliGaultney/will-the-us-government-shut-down-on" = ["YES", "NO"]

[GROUPS."Pence Runs 2024"]
"https://manifold.markets/NcyRocks/will-mike-pence-run-for-president-i" = ["YES", "NO"]
"https://manifold.markets/BRTD/will-mike-pence-run-for-president-i-fba3872c8e95" = ["YES", "NO"]

[GROUPS."N.C. Young misresolution"]
"https://manifold.markets/NcyRocks/will-anyone-successfully-contest-on-8245fe15603f" = ["YES", "NO", "NO"]
"https://manifold.markets/NcyRocks/will-anyone-successfully-contest-on-572e14fcecea" = ["YES", "YES", "NO"]

[GROUPS."Abbot Runs 2024"]
"https://manifold.markets/BTE/will-greg-abbott-seek-the-gop-nomin" = ["YES", "NO"]
"https://manifold.markets/NcyRocks/will-greg-abbott-run-for-president" = ["YES", "NO"]

[GROUPS."N.C. Young get married"]
"https://manifold.markets/NcyRocks/will-i-get-married-by-2035" = ["YES", "NO", "NO"]
"https://manifold.markets/NcyRocks/will-i-ever-get-married" = ["YES", "YES", "NO"]

[GROUPS."Nation Pary New Zealand"] # ardern wins, national party wins, other
"https://manifold.markets/Nostradamnedus/will-jacinda-ardern-be-the-prime-mi" = ["YES", "NO", "NO"]
"https://manifold.markets/NcyRocks/will-the-national-party-form-a-gove" = ["NO", "YES", "NO"]

[GROUPS."Bernie Runs"]
"https://manifold.markets/LarsDoucet/will-bernie-sanders-seek-the-democr" = ["YES", "NO", "NO"]
"https://manifold.markets/NcyRocks/will-bernie-sanders-run-for-preside" = ["YES", "YES", "NO"]

[GROUPS."Moon Landing"] 
"https://manifold.markets/AmmonLam/will-nasa-land-a-person-on-the-moon-97aac7e1ff3b" = ["YES", "NO", "NO", "NO"]
"https://manifold.markets/BoltonBailey/will-nasa-land-a-person-on-the-moon" = ["YES", "YES", "NO", "NO"]
"https://manifold.markets/Treldman/will-there-be-a-new-human-moon-land" = ["YES", "YES", "YES", "NO"]