SUPABASE_APIKEY= "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InB4aWRyZ2thdHVtbHZmcWF4Y2xsIiwicm9sZSI6ImFub24iLCJpYXQiOjE2Njg5OTUzOTgsImV4cCI6MTk4NDU3MTM5OH0.d_yYtASLzAoIIGdXUBIgRAGLBnNow7JG2SoaNMQ8ySg"

# APIKEY = "057fa467-501a-47b8-9b23-36041d1a8388"
# USERNAME = "Bot"

# APIKEY = "218fc836-c568-4e88-b12a-eaef0f538431"
# USERNAME = "NeonNuke"
# FIREBASE_APIKEY = "eyJhbGciOiJSUzI1NiIsImtpZCI6IjE2ZGE4NmU4MWJkNTllMGE4Y2YzNTgwNTJiYjUzYjUzYjE4MzA3NzMiLCJ0eXAiOiJKV1QifQ.eyJuYW1lIjoiTmVvbiBOdWtlIiwicGljdHVyZSI6Imh0dHBzOi8vbGgzLmdvb2dsZXVzZXJjb250ZW50LmNvbS9hL0FMbTV3dTJ5cXFuZHFNZzBOU0tfNlZSN0hFZ2UzeFBuQUpTOExHeVUwd0Y0dXc9czk2LWMiLCJpc3MiOiJodHRwczovL3NlY3VyZXRva2VuLmdvb2dsZS5jb20vbWFudGljLW1hcmtldHMiLCJhdWQiOiJtYW50aWMtbWFya2V0cyIsImF1dGhfdGltZSI6MTY3MzAxOTE0NCwidXNlcl9pZCI6ImdmVVJpaUdGWWVVb1V6dXpUdWJrTmFXZFN2TTIiLCJzdWIiOiJnZlVSaWlHRlllVW9VenV6VHVia05hV2RTdk0yIiwiaWF0IjoxNjgyMTEyODM2LCJleHAiOjE2ODIxMTY0MzYsImVtYWlsIjoidW5yYWh1bGJlYXRhYmxlQGdtYWlsLmNvbSIsImVtYWlsX3ZlcmlmaWVkIjp0cnVlLCJmaXJlYmFzZSI6eyJpZGVudGl0aWVzIjp7Imdvb2dsZS5jb20iOlsiMTA4NjY4ODIyMjc4NDA5MDI3NjE0Il0sImVtYWlsIjpbInVucmFodWxiZWF0YWJsZUBnbWFpbC5jb20iXX0sInNpZ25faW5fcHJvdmlkZXIiOiJnb29nbGUuY29tIn19.ArXyfPPKL6boUzVxBrvV6_TOykdzgcy1dZsRBM3lGq-_8QYLQm-vUJeIG6seEQ1i_86GaA-z8f5Fr4EvDB41wuYJsoH8VJW467JaFH3bM7KyMDnWbuOi_-VVYJi82xSLPiLFHxTutstO1zGGAfdwBSwVJF6MpTKbNXKnUycyIcOPrM64qBUL-XzM5vT8pkZQ5lyztQ6uwn5aJ_xDIavYW2qlCXnSxspiOZMRd8GtO4yzbQI0oe_BV_NkcvD6eK7sDKITVas_TPTQRFfsThe-366v1PhDCcTKd_4QRWP_tAZVqXBpbNiWNXC9RzJ7MuJZjnUFXVV2hX_g2-JqwzvctQ"

# APIKEY = "c7d5892e-6277-43d9-99fa-6c36b40d3f50"
# USERNAME = "BottieMcBotface"

APIKEY = "13f50b4f-f6e4-4ff8-b80e-accbbcc57673"
USERNAME = "Kendall"
FIREBASE_APIKEY = "eyJhbGciOiJSUzI1NiIsImtpZCI6IjE2ZGE4NmU4MWJkNTllMGE4Y2YzNTgwNTJiYjUzYjUzYjE4MzA3NzMiLCJ0eXAiOiJKV1QifQ.eyJuYW1lIjoiQWxleCBTbWl0aCIsInBpY3R1cmUiOiJodHRwczovL2xoMy5nb29nbGV1c2VyY29udGVudC5jb20vYS9BR05teXhZVUxPVVI5MVhjZVJxMEhHcWw1c2ZQcUtvT1BNYmhWLVV3SUY2dj1zOTYtYyIsImlzcyI6Imh0dHBzOi8vc2VjdXJldG9rZW4uZ29vZ2xlLmNvbS9tYW50aWMtbWFya2V0cyIsImF1ZCI6Im1hbnRpYy1tYXJrZXRzIiwiYXV0aF90aW1lIjoxNjgyMTExMzAxLCJ1c2VyX2lkIjoiNkJrblZIU05GQ1lOdEhnczZta1JWOWFYbTFUMiIsInN1YiI6IjZCa25WSFNORkNZTnRIZ3M2bWtSVjlhWG0xVDIiLCJpYXQiOjE2ODIxMTYzNTMsImV4cCI6MTY4MjExOTk1MywiZW1haWwiOiJ1bnJhaHVsYmVhdGFibGVAaWNsb3VkLmNvbSIsImVtYWlsX3ZlcmlmaWVkIjp0cnVlLCJmaXJlYmFzZSI6eyJpZGVudGl0aWVzIjp7Imdvb2dsZS5jb20iOlsiMTA2NDYxNTc0NjQxMjE3OTk3Mzg4Il0sImVtYWlsIjpbInVucmFodWxiZWF0YWJsZUBpY2xvdWQuY29tIl19LCJzaWduX2luX3Byb3ZpZGVyIjoiZ29vZ2xlLmNvbSJ9fQ.VHkiOBrQ3lbMHftX5zpVg5BxFz31TkRGPkVXy5ZRa91yDkmi3QVCk7x_vwgD5UiqUBTloe0XsfIUzfXEaSizVrWRAvx3fx9Pni7RvcgU2Teb2g0j7zniXfqkKw-2ZZg4VqcnafgUjhQReen3XblAKZjecDWlvyHgI28AhKefGu-98wtxo8WAqiJz5rExubV_nBdPt460pj0K4NQYeI5GoSBPnQ1XgyTXmStsxzdwk4oKPpHz1wRLXqrx6U3yUctyqmz9zOtxQUdXPfuEltg43mxMvGWxJx6jIxCLuddHHTcBjrOewiEBZICHAbQt3pYctc5yPvS188ar2lLLs3nkRQ"

[SMARTUSERS]
"Botlab" = "ilJdhpLzZZSUgzueJOs2cbRnJn82"
"Michael Wheatley" = "jO7sUhIDTQbAJ3w86akzncTlpRG2"
"v" = "w1knZ6yBvEhRThYPEYTwlmGv7N33"
"acc" = "BhNkw088bMNwIFF2Aq5Gg9NTPzz1"
"Spindle" = "jOl1FMKpFbXkoaDGp2qlakUxAiJ3"
"Gurkenglas" = "MxdyEeVgrFMTDDsPbXwAe9W1CLs2"
"GeorgeVii" = "IEVDP2LTpgMYaka38r1TVZcabWS2"
"Arrrr" = "dNgcgrHGn8ZB30hyDARNtbjvGPm1"
"Yev" = "Y8xXwCCYe3cBCW5XeU8MxykuPAY2"
"Gigacasting" = "wjbOTRRJ7Ee5mjSMMYrtwoWuiCp2"
"William Hargraves" = ["EFzCw6YhqTYCJpeWHUG6p9JsDy02", "UN5UGCJRQdfB3eQSnadiAxjkmRp2"]
"Bobyouname" = "QQodxPUTIFdQWJiIzVUW2ztF43e2"
"firstuserhere" = "zgCIqq8AmRUYVu6AdQ9vVEJN8On1"
"Simon" = "K2BeNvRj4beTBafzKLRCnxjgRlv1"
"nfd" = "BB5ZIBNqNKddjaZQUnqkFCiDyTs2"
"Catnee" = ["kydVkcfg7TU4zrrMBRx1Csipwkw2", "I8VZW5hGw9cfIeWs7oQJaNdFwhL2", "wuOtYy52f4Sx4JFfT85LpizVGsx1", "rVaQiGT7qCRfAD9QDQQ8SHxvvuu2", "U7KQfJgJp1fa35k9EXpQCgvmmjh1", "w07LrYnLg8XDHySwrKxmAYAnLJH2", "n820DjHGX9dKsrv0jHIJV8xmDgr2"]
# "NeonNuke" = 
"Marcus Abramovitch" = "b3WDWY8TdrhQKKNuJkNuvQKwHWE3"
"jack" = ["YGZdZUSFQyM8j2YzPaBqki8NBz23", "CB4w5sHsJxQyoyO3mESajTSTugC2"]

[dumbUsers]
"Spindle" = "jOl1FMKpFbXkoaDGp2qlakUxAiJ3"